name: notes
description: Simple notes application
version: 1.0.0+1

environment:
  sdk: any

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
